### ISSUE TITLE
Peer Feedback

### ISSUE THREAD

**Issue by jthompson18** [SalomonSmeke/TwitterParserExcercise#1]
Overall this is very solid. The code is well written and I like the ease of adding new rules from a user perspective. But it adds a lot of extra complexity. In a complete product, the higher the order of complexity the more likely bugs are the appear.

My only critique is that I'd like to see more tests around the rule extension feature. And some sort of written spec for what rules are valid/invalid, how dupe rules are handled, where/how rules are removed, and so on.

@SalomonSmeke, I've got a few questions for you.
What was your justification/reasoning for adding in the rule extension feature?

Who is the rule extension feature for?

How are you persisting rules? In a complete product this would be abstracted away from this module. I imagine it living somewhere else and having a rule builder taking the rules from the db and building the rule set that the message parser would use. In this implementation is there still a purpose the rule extension feature? 

Where do you see this module fitting into a complete messaging product?

These questions are meant to make you think about the project as a piece of a product as well as document your reasonings for your approach versus some other implementation.

**Comment by SalomonSmeke** [comment]
First to answer your critiques:

You're 100% correct. This would never ever be production used. And I didn't have enough time to finish tests. You're indeed quite perceptive.

Now your questions:

Justification?

Challenge and because it'd be fun to do. I hate how dumb the twitter rules are and didn't want to hardcode them because id feel dirty saying (for example) the letter ñ isn't valid in a url. Regex would be hard to maintain for other devs who don't know it. So I decided to....

Target audience?

Hit up them yung developers who just want to try some text with a robust easy to edit mechanism. Please! Write a regex. But use this rule system to check if your output is valid. Cause its easy.

Persistence?

Lol. databases. try doing this and learning THOSe in a week. You're right, of course. But rule is actually part of the text processing, so its verrrry necessary.

Where do you see it in a messaging product?

Hopefully nowhere in the product. Hopefully in the developer's computer.

I hope this answers :) thanks for the comments && much love.

**Comment by leandrohss** [comment]
First, congrats for such a great job!!! I like the way you handle your Parser.
I’m going to give you some suggestions; I hope most of those suggestions find you well!

**\* General suggestions ***
- Try to use doc comments (/*\* _/) instead of simple comments (/_ */) for non-trivial public methods and classes (when needed)
- There is no blank line space in methods. I’d suggest using a blank line between variables and loops, or something else that divide your methods into sub-blocks in a visual way. For example, the class ImmutableItem has no blank space. Also, you could divide your attributes according to the type (String, int, etc) and put a blank line between them. That will make your code easier to read.

**\* Class Rule ***
- I'd like you have a Javadoc comments explaining what means a Rule in your application. Also, maybe MessageRule or TwitterRule would be a clearer name.
- In the constructor’s arguments, I would use “String ... tokens” instead of “String [] tokens”. That will allow the user to use either a single String or an array of String;
- You have used “if  (behavior=="TEXT")” and  “if  (behavior=="SPLIT")”.  You should make SPLIT and TEXT constants in your app. You might create a class Behavior or just create public constants in your class.

**\* Class Rules ***
- What don’t you put the method addRule() in that class? That would make more sense for your purpose;
- If you don’t need that method I just said, you could make this class static. So you just need to use Rules.getRules() in order to get them.

**\* StringIronBox ***
- Make the inner class “immutableItem” capitalized at the first letter. That’s just a Java’s Standard;
- In the method “contains(String text), you could use only this: “return list.contains(new immutableItem(text)”. The Else statement is unnecessary.
- The same about the method equals():  “return in.toString() == this.item”. And you should use “equals” instead of “==” for strings.

**\* Tweet Class ***
- I guess an empty tweet makes no sense. So, you should throw an exception instead of just a warning message;
- If you do what I just said, there will be no need to return anything in the method parseIn().

**\* Types ***
- I would say the 2 private methods are unnecessary; you could use their implementations inside the 2 public methods. But, that is not really a problem.

**\* DataHandler Class ***
- Throw an exemption for null messages in the constructor;
- In the method “categorize”, change the argument's name “string” to “word” or write a comment explaining what is that “string”.

That's it. It was great see your solution!

**Comment by SalomonSmeke** [comment]
@leandrohss 

Hey hey! Great to see you! Thanks for being so thorough.

Im gonna be honest here: you put more thought into my project than I did! ha! all your suggestions make sense and are great. (I think there is one exception but ill go into that once I fix them).

Thanks for being so constructive and detailed, again.

Please note: much of this was coded in a super frantic rush, don't hate me for its shortcomings :)

we should do group projects sometime!

**Comment by leandrohss** [comment]
Yeah, we didn't have much time to do it, but you still did a great job.
Your code was one of the most complete that I've found here. So, it was enjoyable to read it!

**Comment by SalomonSmeke** [comment]
Thanks!

**Comment by SalomonSmeke** [comment]
ok. we like 80% there fam. @leandrohss @jthompson18

**Comment by SalomonSmeke** [comment]
Done with what I agreed with!
