### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by cartfisk** [SalomonSmeke/TwitterParserExcercise#2]
Like jthompson18 mentioned, I like the extensibility of the rules engine but it could be significantly simplified by simply providing support for interchangeable regexes.

Your code is very thorough, I like that you included overrides for toString, etc. but I think code readability could be improved. A bit more separation and commenting at the beginning of files would likely vastly improve readability.

**Comment by SalomonSmeke** [comment]
Actually! the whole idea was to not use regex. to be the ANTI regex. The point was: the user can place in a rule super easily, and not have to make a regex until later in the production cycle.

REGEX is generally not very readable. In the comments of the code I have some sections going "Yeah, this isnt clean, but that is because its for the user. not you"

Im definitely going to work to make the code more readable, though.

**Comment by cartfisk** [comment]
Fair enough I guess. I think regexes are cool, and I agree they can be hard to read, but worst case you throw in a comment line saying "blah blah this regex pulls A-Z, a-z, 0-9, etc. and trashes the rest". By nature they are hard to read but providing an explanation requires minimal effort.

**Comment by SalomonSmeke** [comment]
oh for sure. but for example. here is a phone validation regex:

^(?:(?:+?1\s_(?:[.-]\s_)?)?(?:(\s_([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9])\s_)|([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s_(?:[.-]\s_)?)?([2-9]1[02-9]|[2-9][02-9]1|[2-9][02-9]{2})\s_(?:[.-]\s_)?([0-9]{4})(?:\s_(?:#|x.?|ext.?|extension)\s_(\d+))?$

as a developer. for testing. you dont want to write that.

**Comment by SalomonSmeke** [comment]
anyways. ill update this as i go

**Comment by SalomonSmeke** [comment]
labeled as dupe since the part thats a problem and needs to be fixed is part of the other issue!
